---

- hosts: all
  become: true
  pre_tasks:

  - name: update repository index (CentOS)
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "RedHat"


  - name: Update reposito updates (Ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

- hosts: all
  become: true
  roles:
    - base

- hosts: workstation
  become: true
  roles:
    - workstation

- hosts: web_server
  become: true
  roles:
    - web_server

- hosts: db_server
  become: true
  roles:
    - db_server

- hosts: file_server
  become: true
  roles:
    - file_server
