- name: install mariadb  server package (CentOS)
  tags: CentOS,db,mariadb
  dnf:
    name: mariadb
    state: latest
  when: ansible_distribution == "Red Hat"

- name:	install	mariadb server
  tags:	Ubuntu,db,mariadb
  apt:
    name: mariadb-server
    state: latest
  when:	ansible_distribution ==	"Ubuntu"

